version: "3"

services:
    php:
        build:
            context: './php'
        networks:
            - backend
        volumes:
            - ./www/:/var/www/html
        container_name: "php-opencart"

    nginx:
        image: nginx:latest
        restart: always
        depends_on:
            - php
            - db
            - ftp
        networks:
            - backend
            - frontend
        ports: 
            - "80:80"
        volumes:
             - ./www:/var/www/html
             - ./nginx.conf:/etc/nginx/nginx.conf
             - ./opencart.conf:/etc/nginx/conf.d/opencart.conf
        container_name: "nginx-opencart"

    db:
        image: mysql:5.7
        restart: always
        ports:
            - "3306:3306"
        volumes:
            - ./mysql/:/var/lib/mysql
        networks:
            - backend
        environment:
            MYSQL_ROOT_PASSWORD: linux
            MYSQL_DATABASE: dev
        container_name: "db-opencart"

    ftp:
        image: hauptmedia/proftpd
        restart: always
        ports:
            - "21:21"
        networks:
            - backend
        environment:
            FTP_USERNAME: dev
            FTP_PASSWORD: dev
        volumes:
            - ./www:/ftp
        container_name: "ftp-opencart"

networks:
    backend:
    frontend:
